// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.590
package pub_intro

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Intro() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col prose-sm prose-a:font-extrabold prose-a:underline\"><div class=\"mb-4 mt-8 basis-1/2 rounded-box bg-accent p-4 shadow-2xl\n      shadow-accent/20 bg-opacity-30\"><p class=\"text-justify\"><strong class=\"text-xl\">Welcome!</strong><br>This is my personal Blog. Originally, this blog started as an example project to create web apps using only <strong>HTMX, Golang and Tailwind CSS</strong>. But I love the result soo much that I decided to just reuse the project as the basis of my (already planned) blog.<br><br>I open sourced the code of this very blog in my <a href=\"https://github.com/muhwyndhamhp/marknotes\">GitHub.</a> Feel free to use it as it suits you, if you like what you've seen here!</p></div><div class=\"my- mt-4 basis-1/2 rounded-box bg-info p-4 shadow-2xl shadow-info/20 bg-opacity-30\"><p class=\"text-justify\"><strong class=\"text-xl\">About Me</strong><br>My name is Wyndham, and I'm a growing Software Engineer with a delightful mix of Android and Backend wizardry!🪄🧙🏻\u200d♀️<br><br>My tech toolbox consist of <strong>Kotlin, Golang</strong>, with a dash of <strong>Python, Ruby-on-Rails, and Javascript</strong>. If you're on the hunt for an Android virtuoso who's also got some backend boogie, look no further. <a href=\"/contact\">Hit me up!</a></p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
