// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.590
package pub_themepicker

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fmt"
import "github.com/muhwyndhamhp/marknotes/pub/assets"

func triggerTheme(theme string, isDark bool) string {
	return fmt.Sprintf("on click window.setMkTheme('%s', %t)", theme, isDark)
}

func ThemePicker(themes []ThemeOption) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div role=\"button\" class=\"btn btn-ghost btn-circle\" aria-labelledby=\"themeLabel\"><label class=\"swap swap-rotate\"><input id=\"dark-toggle\" type=\"checkbox\" _=\"\n               on change(input) \n                  get the (checked of the closest &lt;input/&gt;) \n               then\n                  js(it) \n                     window.toggleDarkMode(it); \n                     window.setMkTheme(null, !it); \n                  end\n               end\n\n               on load call window.initialState() end\n               \">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = pub_assets.Sun(20).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = pub_assets.Moon(20).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"themeLabel\" class=\"hidden\">Theme Darkmode Toggle and Selection</div></label></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
